"""Initial schema

Revision ID: dc388b5497ca
Revises: 
Create Date: 2025-11-13 23:24:36.431321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc388b5497ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_policy_updated', 'policies', ['updated_at'], unique=False)
    op.create_table('policy_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('old_version', sa.Integer(), nullable=True),
    sa.Column('new_version', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_audit_log_policy_id'), 'policy_audit_log', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_audit_log_timestamp'), 'policy_audit_log', ['timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_env_ts', 'signals', ['service', 'environment', 'timestamp'], unique=False)
    op.create_index(op.f('ix_signals_environment'), 'signals', ['environment'], unique=False)
    op.create_index(op.f('ix_signals_service'), 'signals', ['service'], unique=False)
    op.create_index(op.f('ix_signals_timestamp'), 'signals', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_timestamp'), table_name='signals')
    op.drop_index(op.f('ix_signals_service'), table_name='signals')
    op.drop_index(op.f('ix_signals_environment'), table_name='signals')
    op.drop_index('idx_service_env_ts', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_policy_audit_log_timestamp'), table_name='policy_audit_log')
    op.drop_index(op.f('ix_policy_audit_log_policy_id'), table_name='policy_audit_log')
    op.drop_table('policy_audit_log')
    op.drop_index('idx_policy_updated', table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
